"""Tiered alerting for the live harness (docs/05 §6).

P1  -> GitHub issue in this repository (labelled, deduped by open title) plus
       the optional webhook. Issues reach the owner's normal GitHub
       notifications — the push channel that exists before any secret is set.
P2  -> the run's step summary plus the optional webhook.

Degrades gracefully: outside Actions it just prints; smoke runs (LIVE_SMOKE=1)
never file issues or hit the webhook.
"""

from __future__ import annotations

import json
import os
import urllib.request

FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"


def _repo() -> str:
    return os.environ.get("GITHUB_REPOSITORY", "")


def _token() -> str:
    return os.environ.get("GITHUB_TOKEN", "")


def _api(method: str, path: str, payload=None):
    req = urllib.request.Request(
        f"https://api.github.com{path}",
        data=json.dumps(payload).encode() if payload is not None else None,
        method=method,
        headers={
            "Authorization": f"Bearer {_token()}",
            "Accept": "application/vnd.github+json",
            "User-Agent": "nafa-live-harness",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        body = r.read()
        return json.loads(body) if body else {}


def _webhook(text: str) -> None:
    url = os.environ.get("ALERT_WEBHOOK_URL", "")
    if not url:
        return
    try:
        req = urllib.request.Request(
            url,
            data=json.dumps({"text": text}).encode(),
            headers={"Content-Type": "application/json"},
        )
        urllib.request.urlopen(req, timeout=15)
    except Exception as exc:  # noqa: BLE001 - alerting must never crash a cycle
        print(f"alert: webhook failed: {exc}")


def step_summary(md: str) -> None:
    path = os.environ.get("GITHUB_STEP_SUMMARY")
    if path:
        with open(path, "a", encoding="utf-8") as f:
            f.write(md + "\n")


def alert(level: str, title: str, body: str = "", dedupe: bool = True) -> None:
    """level 'P1' or 'P2'. Never raises — a broken alert channel must not
    take the cycle down with it (the deadman workflow is the backstop)."""
    text = f"[{level}] {title}" + (f"\n{body}" if body else "")
    print(text, flush=True)
    step_summary(f"**{level} — {title}**\n\n{body}\n")
    if os.environ.get("LIVE_SMOKE") == "1":
        return
    _webhook(text)
    if level != "P1" or not (_repo() and _token()):
        return
    try:
        label = "live-p1"
        try:
            _api("POST", f"/repos/{_repo()}/labels",
                 {"name": label, "color": "b60205",
                  "description": "live harness P1 incident"})
        except Exception:  # noqa: BLE001 - label already exists
            pass
        if dedupe:
            issues = _api(
                "GET", f"/repos/{_repo()}/issues?state=open&labels={label}&per_page=100")
            if any(i.get("title") == f"[P1] {title}" for i in issues):
                print("alert: matching open P1 issue exists; not duplicating")
                return
        _api("POST", f"/repos/{_repo()}/issues",
             {"title": f"[P1] {title}", "body": (body or title) + FOOTER,
              "labels": [label]})
    except Exception as exc:  # noqa: BLE001
        print(f"alert: could not file GitHub issue: {exc}")
