// Plain-English explanations for every abbreviation and financial term the
// console shows. Written for an owner who is not a finance professional:
// what it means, then (in `here`) what it means in this console.

export interface Entry {
  /** Heading of the info card, e.g. "ATR — Average True Range". */
  title: string;
  /** One to three short sentences, no jargon. */
  plain: string;
  /** Optional: how this console uses it, or a worked example. */
  here?: string;
}

export const TERMS = {
  // ───────── money and the portfolio ─────────
  equity: { title: 'Equity', plain: 'The total value of the portfolio right now: cash plus the market value of every share held.', here: 'Both books start at $100,000, so $90,000 means the portfolio is down 10%.' },
  pnl: { title: 'P&L — profit and loss', plain: 'How much money was made (+) or lost (−). Green with a + is a gain; red with a − is a loss.' },
  todayPnl: { title: 'Today’s P&L', plain: 'How much the portfolio’s value changed since the previous trading day’s close.' },
  unrealized: { title: 'Unrealized P&L', plain: 'The gain or loss on shares you still own, measured at today’s price. It is only “on paper” — it can still change until you sell.' },
  realized: { title: 'Realized P&L', plain: 'Profit or loss that is locked in because the shares were sold. Once realized, it no longer moves.' },
  drawdown: { title: 'Drawdown', plain: 'How far the portfolio has fallen from its highest value so far, in percent. −11% means it is 11% below its best point.', here: 'It measures how painful the ride is, not the final result.' },
  maxDrawdown: { title: 'Max drawdown', plain: 'The worst fall from a high point to a low point seen so far.' },
  peak: { title: 'Peak', plain: 'The highest value the portfolio has reached. Drawdown is measured from here.' },
  killLine: { title: 'Kill line (−25%)', plain: 'A hard safety limit: if the portfolio falls 25% from its peak, trading stops automatically and a human must decide what happens next.' },
  refDD: { title: 'Reference drawdown (−16.2%)', plain: 'The worst fall the strategy had in its out-of-sample test (2023–2026). A yardstick: live results much worse than this would be a warning sign.' },
  exposure: { title: 'Exposure (invested)', plain: 'The share of the portfolio held in stocks rather than cash. 95% means $95 of every $100 is invested.' },
  cash: { title: 'Cash', plain: 'Money not invested in any stock. It earns nothing here (no interest, by design).' },
  weight: { title: 'Weight', plain: 'How big one holding is compared with the whole portfolio. 14% means 14 cents of every dollar is in that stock.' },
  posCap: { title: 'Position cap (18%)', plain: 'A safety limit: no single stock may grow above 18% of the portfolio, so one company cannot sink the whole book.', here: 'The red tick on each weight bar marks the cap.' },
  avgCost: { title: 'Average cost', plain: 'The average price paid per share for the shares you still hold, across all purchases.' },
  last: { title: 'Last price', plain: 'The most recent closing price the system has for the stock.' },
  value: { title: 'Market value', plain: 'What the holding is worth now: number of shares × last price.' },
  shares: { title: 'Shares', plain: 'How many shares of the company are held. The system only buys whole shares.' },
  maxPositions: { title: 'Positions (15 max)', plain: 'How many different stocks are held. The strategy holds at most 15 at once to stay diversified.' },
  expMax: { title: 'EXP_MAX', plain: 'The most the agent may invest in total: 95% of the portfolio. The rest always stays as cash.' },
  grossCap: { title: 'Gross exposure cap', plain: 'An extra limit you can set on how much may be invested in total. When it is below what the agent wants, new buys are blocked or trimmed.' },
  turnover: { title: 'Turnover', plain: 'The value of the night’s buys plus sells as a share of the portfolio. More turnover means more trading and more costs.', here: 'A night may not trade more than 75% of the portfolio.' },
  netCash: { title: 'Net cash need', plain: 'Money spent on buys minus money received from sells at the next open. “Freed” means sells bring in more than buys spend.' },
  cashLeft: { title: 'Cash left (estimated)', plain: 'Roughly how much cash remains after tonight’s orders fill, using yesterday’s closing prices.' },
  fees: { title: 'Fees', plain: 'What the broker charges per trade. The Alpaca account used here charges no commission.' },
  fifo: { title: 'FIFO lots', plain: 'Each purchase is a “lot”. FIFO — first in, first out — means the oldest shares are counted as sold first. That decides the profit on each sale.' },
  roundTrip: { title: 'Round trip', plain: 'One complete trade: buy a stock, then sell it. Its result is the realized profit or loss.' },
  winRate: { title: 'Win rate', plain: 'The share of closed trades that made money.', here: 'Momentum strategies often win fewer than half their trades and rely on the winners being much bigger than the losers.' },
  avgWinLoss: { title: 'Average win / average loss', plain: 'The typical profit on a winning trade compared with the typical loss on a losing one.' },
  payoff: { title: 'Payoff ratio', plain: 'Average win divided by average loss. Above 1 means winning trades are bigger than losing ones.' },
  profitFactor: { title: 'Profit factor', plain: 'Total money won on winning trades divided by total money lost on losing trades. Above 1 means profitable overall; 0.5 means $1 lost for every 50 cents won.' },
  dividend: { title: 'Dividend', plain: 'A cash payment a company makes to its shareholders out of its profits.' },
  withholding: { title: 'Withholding (30%)', plain: 'US tax taken automatically from dividends paid to non-US investors (rate set by the W-8BEN form).' },
  benchmark: { title: 'NASDAQ Composite (IXIC)', plain: 'An index of almost every stock listed on NASDAQ — the market average this strategy tries to beat. IXIC is its ticker code.' },
  rebased: { title: 'Rebased to $100k', plain: 'Every line is scaled to start at the same $100,000, so you can compare their shapes directly.' },
  sinceStart: { title: 'Since start', plain: 'Measured from the first day of the live record (the twin’s start date).' },

  // ───────── books and environments ─────────
  model: { title: 'MODEL book', plain: 'What the agent’s rules say the portfolio should hold: a simulated “twin” that fills every order at the official opening price.', here: 'This is the official record of the strategy.' },
  account: { title: 'ACCOUNT book', plain: 'What the broker account actually holds. It should match the Model book closely; small gaps come from whole shares and real fill prices.' },
  drift: { title: 'Drift', plain: 'The gap between the Model book and the real account. Small drift is normal; a large or growing gap needs a look.', here: 'Alert band: 1.5% of the portfolio, or ±2 shares / 5% per stock.' },
  twin: { title: 'The twin', plain: 'A replay of the frozen strategy from the start date using real prices. It is the reference every real trade is compared with.' },
  ghost: { title: 'GHOST mode', plain: 'Rehearsal: no broker and no real orders. Every night the system runs as if it were trading, to prove it is reliable before any money is involved.' },
  paper: { title: 'PAPER mode', plain: 'Trading with pretend money in a simulated broker account (Alpaca paper), at real market prices.' },
  live: { title: 'LIVE mode', plain: 'Trading with real money in a real brokerage account.' },
  booktag: { title: 'Book tag', plain: 'Shows which set of numbers a panel uses: MODEL (the strategy’s twin) or ACCOUNT (the real broker account, in violet).' },

  // ───────── orders and execution ─────────
  moo: { title: 'MOO · opg — market on open', plain: 'An order that executes in the opening auction at 09:30 New York time, at the official opening price. “opg” is the broker’s code for it.' },
  nextOpen: { title: 'Next open', plain: 'The next trading morning (09:30 ET) when tonight’s orders will execute.' },
  refClose: { title: 'Reference close', plain: 'The latest closing price, used to estimate how many shares an order buys and what it is worth.' },
  estValue: { title: 'Estimated value', plain: 'Shares × reference close. The real amount depends on the next opening price.' },
  officialOpen: { title: 'Official open', plain: 'The exchange’s opening-auction price — the price a market-on-open order is meant to get.' },
  decisionClose: { title: 'Decision close', plain: 'The closing price on the day the agent decided to trade. Orders fill at the next morning’s open, so the two can differ.' },
  fillPrice: { title: 'Fill price', plain: 'The price the order actually executed at.' },
  slippage: { title: 'Slippage', plain: 'The difference between the price hoped for (the official open) and the price actually got. A + means it cost money.', here: 'Measured in basis points (bps); the target is ≤ 10 bps per trade.' },
  bps: { title: 'bps — basis points', plain: 'One hundredth of one percent. 100 bps = 1%. 5 bps on a $10,000 order is $5.' },
  shortfall: { title: 'Implementation shortfall', plain: 'The difference between the decision-day close and the final fill price: the full cost of trading at the next morning’s open instead of at the decision.' },
  clientOrderId: { title: 'Client order id', plain: 'A unique label on every order so it can never be sent twice and can be traced from decision to fill.' },
  lifecycle: { title: 'Order lifecycle', plain: 'The steps every order goes through: intent → safety checks → planned → accepted by the broker → filled → reconciled.' },
  guardrails: { title: 'Guardrails', plain: 'Automatic safety rules every order must pass (position cap, daily turnover, trading-volume limit, exclusions). A failing order is blocked, not sent.' },
  advCap: { title: 'ADV cap', plain: 'ADV is a stock’s average daily trading value. An order may not exceed 5% of it, so our own order does not push the price around.' },
  pauseEntries: { title: 'pause_entries', plain: 'A control that blocks new buys while letting sells and stop-losses continue.' },
  excluded: { title: 'excluded_symbols', plain: 'Stocks that may not be bought (for example because they failed the Sharia screen). If one is held, it is sold at the next open.' },
  locked: { title: 'Locked', plain: 'The agent may neither buy nor sell this stock until you unlock it.' },
  killSwitch: { title: 'Kill switch', plain: 'The emergency stop: open orders are cancelled and nothing trades until you resume after a checklist.' },
  approval: { title: 'Approval mode (night held)', plain: 'Tonight’s orders wait for your manual release before they are sent to the broker.' },
  halt: { title: 'Reconciliation halt', plain: 'Trading stops automatically when the broker’s holdings do not match what the records say. A human must find the cause and clear it.' },
  reconcile: { title: 'Reconciliation', plain: 'Checking, share for share, that the account holds exactly what it should after the morning’s fills.' },
  submit: { title: 'Submit (19:15 ET)', plain: 'The evening step that sends the night’s orders to the broker for the next morning’s open.' },
  cycleA: { title: 'Cycle A (17:05 ET)', plain: 'The evening step: downloads the day’s prices, checks them, runs the agent and writes tomorrow’s orders into the ledger.' },
  cycleB: { title: 'Cycle B (09:50 ET)', plain: 'The morning step after the open: records what filled and reconciles the account.' },
  intent: { title: 'Intent', plain: 'An order the agent wants to place, before any checks or sending.' },
  source: { title: 'Order source', plain: 'Who asked for the order: the agent, a forced Sharia exit, or you (a manual order).' },

  // ───────── the strategy ─────────
  momentum: { title: 'Momentum', plain: 'The tendency of stocks that have risen strongly in recent months to keep rising for a while. The agent buys the strongest ones and sells when they weaken.' },
  rank: { title: 'Momentum rank', plain: 'A stock’s place in the league table of the universe by recent strength (1 = strongest).' },
  rankExit: { title: 'Rank exit (rank decay)', plain: 'The stock dropped out of the top 30 by momentum, so the agent sells it at the next open.' },
  atr: { title: 'ATR — Average True Range', plain: 'How much a stock typically moves in a day, in dollars or as a % of its price. Jumpy stocks have a high ATR.', here: 'Used to size positions and place stops, so volatile stocks get smaller positions and wider stops.' },
  initialStop: { title: 'Initial stop', plain: 'A safety sell level set below the purchase price (3 × ATR). If the price closes below it, the position is sold to cap the loss.' },
  trailingStop: { title: 'Trailing stop', plain: 'A sell level that follows the price up (5 × ATR below the highest price), locking in part of a gain if the stock turns down.' },
  timeStop: { title: 'Time stop (35 sessions)', plain: 'A position that has not worked out after 35 trading days is sold, freeing the money for a better idea.' },
  nearestExit: { title: 'Nearest exit', plain: 'The sell trigger closest to firing right now — a stop level, a rank exit or the time stop.' },
  sma: { title: 'SMA — simple moving average', plain: 'The average closing price over the last N trading days (50, 100 or 200). A price above its 200-day average is a sign of an up-trend.' },
  high52: { title: '52-week high', plain: 'The highest price in the past year. “2% off the 52w high” means 2% below it; momentum buys stocks near their highs.' },
  sizeLine: { title: 'The “→ 13% line”', plain: 'In an order reason, the target size (weight) the agent’s risk rule gives this stock: riskier stocks get a smaller line.' },
  deRisk: { title: 'De-risk trim', plain: 'Selling part of the holdings to bring total investment down to the target level when the market looks riskier.' },
  regime: { title: 'Regime', plain: 'The overall market mood (trending, choppy, defensive) the agent uses to decide how much to invest.' },
  sentiment: { title: 'Sentiment', plain: 'The agent’s market-mood score from −1 (very defensive) to +1 (strongly risk-on).' },
  adapt: { title: 'adapt() — learning', plain: 'Every 63 trading days the agent re-tunes its settings within fixed limits, based on what worked. You can pause it.' },
  oos: { title: 'OOS — out of sample', plain: 'Results on data the strategy never saw while it was being built (2023–2026). The fairest estimate of how it may behave live.' },
  frozen: { title: 'Frozen strategy', plain: 'The strategy file is locked as it was when it won the test, so the live record is a fair test of exactly that code.' },
  session: { title: 'Session', plain: 'One trading day on the exchange (weekends and holidays are not sessions).' },
  universe: { title: 'Universe', plain: 'The list of stocks the agent is allowed to choose from: the largest NASDAQ companies that pass the Sharia screen.' },
  params: { title: 'Parameters', plain: 'The strategy’s settings (how much to invest, how far away stops are, …), each kept inside fixed bounds.' },

  // ───────── confidence ─────────
  confidence: { title: 'Confidence (0–100)', plain: 'The model’s own conviction in holding the stock now, built from four parts: Signal 40%, Risk room 30%, Regime 20%, Data 10%. It is not a forecast or a promise.', here: 'High ≥ 70 · Medium 40–69 · Low < 40. Computed by the insights step (milestone M3).' },
  signal: { title: 'Signal', plain: 'How strongly the agent still wants the stock: its momentum rank, trend and distance from its high.' },
  riskRoom: { title: 'Risk room', plain: 'How far the stock is from its nearest sell trigger. Little room means a small dip could sell it.' },
  regimeScore: { title: 'Regime (score)', plain: 'How supportive the overall market is right now.' },
  dataScore: { title: 'Data (score)', plain: 'How much the night’s price data for this stock can be trusted (complete, fresh, confirmed by a second source).' },

  // ───────── Sharia ─────────
  aaoifi: { title: 'AAOIFI SS 21', plain: 'The Sharia standard on shares from AAOIFI, the international Islamic finance standards body. It sets which companies are permissible to own.' },
  shariaGrade: { title: 'Sharia grade (A / B / C / F)', plain: 'This console’s quick summary of how comfortably a stock passes the screen.', here: 'A — passes with room to spare · B — passes, but a ratio is within 10 points of a limit · C — needs a ruling or is very close · F — fails or is excluded.' },
  compliant: { title: 'Compliant', plain: 'Passes every layer of the Sharia screen.' },
  underReview: { title: 'Under review', plain: 'The business is in a grey area where scholars differ. It stays in the universe until you rule on it (decision D1).' },
  debtMcap: { title: 'Debt / market cap', plain: 'The company’s interest-bearing debt compared with its total stock-market value. Must stay below 30%.' },
  cashMcap: { title: 'Cash / market cap', plain: 'The company’s cash and interest-earning deposits compared with its stock-market value. Must stay below 30%.' },
  headroom: { title: 'Headroom (pp)', plain: 'How far a ratio is below the 30% limit, in percentage points. A 4% debt ratio has 26 pp of headroom.' },
  pp: { title: 'pp — percentage points', plain: 'The plain difference between two percentages: from 4% to 30% is 26 percentage points.' },
  impermissible: { title: 'Impermissible income', plain: 'Revenue from forbidden activities (such as interest). AAOIFI allows at most 5%. Free data cannot measure it, so it shows as not available until licensed data arrives.' },
  purification: { title: 'Purification', plain: 'Giving to charity the small part of dividends that came from impermissible income, so the rest is clean.' },
  zakat: { title: 'Zakat', plain: 'The yearly obligatory charity on qualifying wealth. A statement arrives with real-money trading.' },
  reviewFlag: { title: 'Review flag', plain: 'Marks a business in a grey area (entertainment, defence, alcohol sales …) that needs your written ruling.' },
  rescreen: { title: 'Re-screen', plain: 'The quarterly re-check of every stock against the Sharia rules (1 Jan, Apr, Jul, Oct). Newly failing stocks are excluded.' },
  watchlist: { title: 'Watchlist', plain: 'Stocks within 3 percentage points of a 30% limit — they could fail at the next re-screen.' },
  businessActivity: { title: 'Business activity screen', plain: 'Checks what the company does; banks, alcohol, gambling and similar businesses are excluded.' },
  commonShare: { title: 'Common share', plain: 'An ordinary share. Preferred shares are excluded because they promise fixed returns.' },
  unlicensed: { title: 'Unlicensed proxy (yfinance)', plain: 'The ratios come from a free data source — fine for testing, not authoritative. Licensed Sharia data arrives with task R3.' },
  ruling: { title: 'Owner ruling (D1)', plain: 'Your written decision on review-flagged stocks: keep or exclude. Due before paper trading starts.' },
  marketCap: { title: 'Market cap', plain: 'The total stock-market value of a company: share price × number of shares.' },

  // ───────── health and operations ─────────
  dataGate: { title: 'Data gate', plain: 'Checks before trading that the day’s price data is complete and consistent. If too much is missing, the day is skipped — never guessed.' },
  coverage: { title: 'Coverage at asof', plain: 'The share of stocks that have a price for the trading day being processed. At least 95% is required.' },
  fetchOk: { title: 'Fetch ok', plain: 'The share of stocks whose price history downloaded at all.' },
  crossSource: { title: 'Cross-source check', plain: 'Closing prices are compared with a second data provider to catch bad data. “Unavailable” means the second source had no price to compare.' },
  asof: { title: 'asof', plain: 'The trading day the numbers refer to (“as of” that day’s close).' },
  determinism: { title: 'Determinism (sha256)', plain: 'Each evening the portfolio is replayed twice and the two results are fingerprinted (a sha256 hash). Identical fingerprints prove the result is reproducible.' },
  ghostGate: { title: 'Ghost gate', plain: 'The test to leave rehearsal: 10 nights in a row where everything ran and the replays matched.' },
  streak: { title: 'Streak', plain: 'How many qualifying nights in a row so far. A failed night resets it.' },
  heartbeat: { title: 'Heartbeat', plain: 'A signal each scheduled step sends when it runs. A missing heartbeat means the step did not run.' },
  deadman: { title: 'Dead-man check', plain: 'A later step that raises an alarm if an earlier one did not leave its record in time.' },
  indexer: { title: 'Indexer', plain: 'The console’s reader: it pulls the ledger every minute and keeps this dashboard up to date.' },
  ledger: { title: 'Ledger', plain: 'The git repository of every record (orders, cycle results, the twin’s state). It is the source of truth; the console only reads it.' },
  commit: { title: 'Commit', plain: 'One saved change in the git ledger, identified by a short code (its SHA).' },
  p1p2: { title: 'P1 / P2 alerts', plain: 'Alert priority. P1 — act now (sent to your phone). P2 — review today.' },
  stale: { title: 'Stale', plain: 'The numbers are older than they should be because a scheduled step failed. They are the last good values, not today’s.' },
  freshness: { title: 'Data age', plain: 'How old the panel’s data is. Amber when it is more than 1 trading day behind, red when more than 2.' },

  // ───────── roadmap and phases ─────────
  phase: { title: 'Phase', plain: 'Stages from rehearsal to real money: Ghost → Paper → Evaluation → private build → Real money. Each has a gate to pass.' },
  gate: { title: 'Gate', plain: 'The conditions that must be met before moving to the next phase.' },
  decisions: { title: 'Owner decisions (D1–D8)', plain: 'Choices only you can make, such as the written Sharia policy (D1) or the real-money broker (D3).' },
} satisfies Record<string, Entry>;

export type TermKey = keyof typeof TERMS;

/**
 * Words and abbreviations inside free text (reasons, notes) that link to an
 * entry. Longer phrases first; matched once per text, whole words only.
 */
export const ALIASES: [RegExp, TermKey][] = [
  [/\btrailing stop\b/i, 'trailingStop'],
  [/\binitial stop\b/i, 'initialStop'],
  [/\btime stop\b/i, 'timeStop'],
  [/\brank (?:decay|exit)\b/i, 'rankExit'],
  [/\bmomentum decay\b/i, 'rankExit'],
  [/\bde-risk\b/i, 'deRisk'],
  [/\b52-?w(?:eek)? high\b/i, 'high52'],
  [/\bATR\b/, 'atr'],
  [/\bSMA ?(?:50|100|200)?\b/, 'sma'],
  [/\bmomentum\b/i, 'momentum'],
  [/\b\d+% line\b/, 'sizeLine'],
  [/\bdata gate\b/i, 'dataGate'],
  [/\bcoverage at asof\b/i, 'coverage'],
  [/\bcross-source\b/i, 'crossSource'],
  [/\bfetch ok\b/i, 'fetchOk'],
  [/\bkill switch\b/i, 'killSwitch'],
  [/\breconciliation\b/i, 'reconcile'],
  [/\bapproval mode\b/i, 'approval'],
  [/\bpause_entries\b/, 'pauseEntries'],
  [/\bexcluded_symbols\b/, 'excluded'],
  [/\bgross_cap\b/, 'grossCap'],
  [/\badv_cap\b|\bADV\b/, 'advCap'],
  [/\bbps\b/, 'bps'],
  [/\bpp\b/, 'pp'],
  [/\bslippage\b/i, 'slippage'],
  [/\bshortfall\b/i, 'shortfall'],
  [/\bdrawdown\b/i, 'drawdown'],
  [/\bexposure\b/i, 'exposure'],
  [/\bturnover\b/i, 'turnover'],
  [/\bdrift\b/i, 'drift'],
  [/\bdebt\/mcap\b|\bdebt \/ market cap\b/i, 'debtMcap'],
  [/\bcash\/mcap\b|\bcash \/ market cap\b/i, 'cashMcap'],
  [/\bheadroom\b/i, 'headroom'],
  [/\bAAOIFI(?: SS 21)?\b/, 'aaoifi'],
  [/\bpurification\b/i, 'purification'],
  [/\bre-?screen\b/i, 'rescreen'],
  [/\bwatchlist\b/i, 'watchlist'],
  [/\breview-flagged\b|\breview flag\b/i, 'reviewFlag'],
  [/\bD1\b/, 'ruling'],
  [/\bCycle A\b/, 'cycleA'],
  [/\bCycle B\b/, 'cycleB'],
  [/\bMOO\b|\bopg\b/, 'moo'],
  [/\bIXIC\b|\bNASDAQ Composite\b/, 'benchmark'],
  [/\bOOS\b/, 'oos'],
  [/\bFIFO\b/, 'fifo'],
  [/\bround trips?\b/i, 'roundTrip'],
  [/\bsha256\b|\bdeterministic\b/i, 'determinism'],
  [/\basof\b/, 'asof'],
  [/\bghost\b/i, 'ghost'],
  [/\btwin\b/i, 'twin'],
  [/\bsessions?\b/i, 'session'],
  [/\bP1\b|\bP2\b/, 'p1p2'],
];
